title: Jessica Mironyuks Blog
theme: minima
author: Jessica Mironyuk
email: jessmiro@uw.edu
description: > # this means to ignore newlines until "baseurl:"
  This blog is a place to show off all of my little hobbies, all the things I enjoy, where to shop at
  and so on !

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  jessmiro # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
